   services:
     app:
       image: devilbox/php-fpm:8.2-work
       container_name: guestbook_app
       restart: always
       volumes:
         - ../guestbook:/var/www/html
       working_dir: /var/www/html
       networks:
         - guestbook_network
       depends_on:
         - postgres

     webserver:
       image: nginx:alpine
       container_name: guestbook_webserver
       restart: always
       volumes:
         - ../guestbook:/var/www/html
         - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       ports:
         - "80:80"
       networks:
         - guestbook_network

     postgres:
       image: postgres:latest
       container_name: guestbook_postgres
       restart: always
       environment:
         POSTGRES_USER: user333
         POSTGRES_PASSWORD: password333
         POSTGRES_DB: guest_book
       ports:
         - "5444:5432"
       volumes:
         - guestBook:/var/lib/postgresql/data
       networks:
         - guestbook_network

   networks:
     guestbook_network:
       driver: bridge

   volumes:
     guestBook: